// Generated by: supabase gen types typescript --project-id ppedomeelrjglzrvnngx > types/database.ts
// Re-run this command after any schema changes.

export type Database = {
  public: {
    Tables: {
      meetings: {
        Row: {
          id: string
          user_id: string
          title: string
          date: string
          summary: string
          decisions: string[]
          blockers: string[]
          follow_up_email: string
          raw_transcript: string
          created_at: string
          fts: unknown
        }
        Insert: {
          id?: string
          user_id: string
          title: string
          date: string
          summary: string
          decisions?: string[]
          blockers?: string[]
          follow_up_email: string
          raw_transcript: string
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          title?: string
          date?: string
          summary?: string
          decisions?: string[]
          blockers?: string[]
          follow_up_email?: string
          raw_transcript?: string
          created_at?: string
        }
        Relationships: []
      }
      action_items: {
        Row: {
          id: string
          meeting_id: string
          user_id: string
          text: string
          owner: string | null
          completed_at: string | null
          created_at: string
        }
        Insert: {
          id?: string
          meeting_id: string
          user_id: string
          text: string
          owner?: string | null
          completed_at?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          meeting_id?: string
          user_id?: string
          text?: string
          owner?: string | null
          completed_at?: string | null
          created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'action_items_meeting_id_fkey'
            columns: ['meeting_id']
            isOneToOne: false
            referencedRelation: 'meetings'
            referencedColumns: ['id']
          },
        ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}
