// Generated by: supabase gen types typescript --project-id ppedomeelrjglzrvnngx > types/database.ts
// Re-run this command after any schema changes.
// This is a placeholder — run the command above to generate the real types.

export type Database = {
  public: {
    Tables: {
      meetings: {
        Row: {
          id: string
          user_id: string
          title: string
          date: string
          summary: string
          decisions: string[]
          blockers: string[]
          follow_up_email: string
          raw_transcript: string
          created_at: string
          fts: unknown
        }
        Insert: {
          id?: string
          user_id: string
          title: string
          date: string
          summary: string
          decisions?: string[]
          blockers?: string[]
          follow_up_email: string
          raw_transcript: string
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          title?: string
          date?: string
          summary?: string
          decisions?: string[]
          blockers?: string[]
          follow_up_email?: string
          raw_transcript?: string
          created_at?: string
        }
      }
      action_items: {
        Row: {
          id: string
          meeting_id: string
          user_id: string
          text: string
          owner: string | null
          completed_at: string | null
          created_at: string
        }
        Insert: {
          id?: string
          meeting_id: string
          user_id: string
          text: string
          owner?: string | null
          completed_at?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          meeting_id?: string
          user_id?: string
          text?: string
          owner?: string | null
          completed_at?: string | null
          created_at?: string
        }
      }
    }
    Views: Record<string, never>
    Functions: Record<string, never>
    Enums: Record<string, never>
  }
}
